#pragma once
class D2Utils
{
public:
	D2Utils() {}
	~D2Utils() {}
	const char* HeroIdToName(char* id);
private:
	/*const char* heroes[115] = {
		"Abaddon",
		"Underlord",
		"Alchemist",
		"Ancient Apparition",
		"Anti-Mage",
		"Arc Warden",
		"Axe",
		"Bane",
		"Batrider",
		"Beastmaster",
		"Bloodseeker",
		"Bounty Hunter",
		"Bremaster",
		"Bristleback",
		"Broodmother",
		"Centaur Warrunner",
		"Chaos Knight",
		"Chen",
		"Clinkz",
		"Crystal Maiden",
		"Dark Seer",
		"Dark Willow",
		"Dazzle",
		"Death Prophet",
		"Disruptor",
		"Doom",
		"Dragon Knight",
		"Drow Ranger",
		"Earth Spirit",
		"Earthshaker",
		"Elder Titan",
		"Ember Spirit",
		"Enchantress",
		"Enigma",
		"Faceless Void",
		"Natures Prophet",
		"Gyrocopter",
		"Huskar",
		"Invoker",
		"Jakiro",
		"Juggernaut",
		"Keeper of the Light",
		"Kunkka",
		"Legion Commander",
		"Leshrac",
		"Lich",
		"Lifestealer",
		"Lina",
		"Lion",
		"Lone Druid",
		"Luna",
		"Lycan",
		"Magnus",
		"Medusa",
		"Meepo",
		"Mirana",
		"Monkey King",
		"Morphling",
		"Naga Siren",
		"Necrophos",
		"Shadow Fiend",
		"Night Stalker",
		"Nyx Assassin",
		"Outworld Devouer",
		"Ogre Magi",
		"Omniknight",
		"Oracle",
		"Pangolier",
		"Phanrom Assassin",
		"Pantom Lancer",
		"Phoenix",
		"Puck",
		"Pudge",
		"Pugna",
		"Queen of Pain",
		"Clockwerk",
		"Razor",
		"Riki",
		"Rubick",
		"Sand King",
		"Shadow Demon",
		"Shadow Shaman",
		"Timbersaw",
		"Silencer",
		"Wraith King",
		"Skywrath Mage",
		"Slardar",
		"Slark",
		"Sniper",
		"Spectre",
		"Spirit Breaker",
		"Storm Spirit",
		"Sven",
		"Techies",
		"Templar Assassin",
		"Terrorblade",
		"Tidehunter",
		"Tinker",
		"Tiny",
		"Treant Protector",
		"Troll Warlord",
		"Tusk",
		"Undying",
		"Ursa",
		"Vengeful Spirit",
		"Venomancer",
		"Viper",
		"Visage",
		"Warlock",
		"Weaver",
		"Windranger",
		"Winter Wyvern",
		"Io",
		"Witch Doctor",
		"Zeus"
	};*/
};